### ISSUE TITLE
Data Practitioner Story: Download and Load Dataset

### ISSUE THREAD

**Issue by Evan2022** [Evan2022/Heritage-Housing-Issues#1]
As a **data practitioner** I want to **download and load the housing dataset into a Jupyter Notebook using pandas** so that **I can analyse and visualize the data**.

**ACCEPTANCE CRITERIA:**

1. The housing dataset is successfully downloaded and loaded into a Jupyter Notebook using pandas.
2. The data is displayed in a clear and organized manner.

**TASKS:**

- [] 1. Download the housing dataset from Kaggle.
- [] 2. Load the dataset into a Jupyter Notebook using pandas.
- [] 3. Load the dataset to make sure its working correctly.
